---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing iptables-legacy on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_iptables_legacy_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "iptables_legacy is defined"
  tags:
    - "iptables-legacy"
- name: "Install iptables-legacy"
  package:
    pkg: "{{ install_iptables_legacy_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "iptables_legacy is defined"
  tags:
    - "iptables-legacy"
