---
- name: "Install iptables-legacy"
  package:
    pkg: "{{ install_iptables_legacy_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  tags:
    - "iptables-legacy"
